// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppLanding: typeof import('./components/AppLanding.vue')['default']
    AppMessages: typeof import('./components/AppMessages.vue')['default']
    AppNotifier: typeof import('./components/AppNotifier.vue')['default']
    AppPanel: typeof import('./components/AppPanel.vue')['default']
    Dark: typeof import('./components/Dark.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
